"""ApiStreamEvent layer -- abstracted streaming events from the LLM API.

Three event types form a discriminated union:

- ``ApiTextDeltaEvent``: incremental text generated by the model
- ``ApiMessageCompleteEvent``: terminal event with final message + usage
- ``ApiRetryEvent``: emitted when the API client retries (rate limit / 5xx)

This is a **harness-level** abstraction. Anthropic SDK emits 7+ granular events
(``content_block_start``, ``content_block_delta``, ``message_stop``, ...); the
API client (Module 3) translates those into our 3 events so downstream
consumers (engine, CLI) only deal with this simpler vocabulary -- and so
swapping the Provider does not ripple beyond the API client layer.
"""

from __future__ import annotations

from typing import Annotated, Literal, TypeAlias

from pydantic import Field

from openharness.protocols._base import StrictModel
from openharness.protocols.messages import ConversationMessage
from openharness.protocols.usage import UsageSnapshot


class ApiTextDeltaEvent(StrictModel):
    """Incremental text from the model during streaming."""

    type: Literal["text_delta"] = "text_delta"
    text: str


class ApiMessageCompleteEvent(StrictModel):
    """Terminal event: the model finished generating.

    Carries the full assembled assistant message (all content blocks), the
    final ``UsageSnapshot``, and the canonical Anthropic ``stop_reason``. The
    engine reads ``stop_reason`` to decide whether to continue the tool loop
    (``tool_use``) or stop (``end_turn`` / ``max_tokens`` / ``stop_sequence``).
    """

    type: Literal["message_complete"] = "message_complete"
    message: ConversationMessage
    usage: UsageSnapshot
    stop_reason: Literal["end_turn", "tool_use", "max_tokens", "stop_sequence"]


class ApiRetryEvent(StrictModel):
    """Emitted by the API client on retryable failure (429 / 5xx / transient).

    Surfaced so the UI can render "retrying..." rather than appearing stalled.
    """

    type: Literal["retry"] = "retry"
    attempt: int = Field(ge=1)
    delay_seconds: float = Field(ge=0)
    error: str


# Discriminated union -- Pydantic dispatches by the ``type`` field at parse time.
# Same pattern as ``ContentBlock`` in content.py.
ApiStreamEvent: TypeAlias = Annotated[
    ApiTextDeltaEvent | ApiMessageCompleteEvent | ApiRetryEvent,
    Field(discriminator="type"),
]
