"""ApiStreamEvent layer -- abstracted streaming events from the LLM API
*plus* engine-emitted tool-execution events.

Five event types form a discriminated union:

- ``ApiTextDeltaEvent``: incremental text generated by the model
- ``ApiMessageCompleteEvent``: terminal event with final message + usage
- ``ApiRetryEvent``: emitted when the API client retries (rate limit / 5xx)
- ``ToolExecutionStartedEvent``: engine begins running a tool the model picked
- ``ToolExecutionCompletedEvent``: engine finished running a tool

The first three are **API-shape** events (translated from Provider SDK chunks
by the API client). The last two are **engine-shape** events emitted by
``run_query`` itself when it dispatches tools. They live in the same union so
UI consumers iterate one stream regardless of source.

This is a **harness-level** abstraction. Anthropic SDK emits 7+ granular events
(``content_block_start``, ``content_block_delta``, ``message_stop``, ...); the
API client (Module 3) translates those into our event vocabulary so downstream
consumers (engine, CLI) only deal with this simpler set -- and so swapping
the Provider does not ripple beyond the API client layer.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal, TypeAlias

from pydantic import Field

from openharness.protocols._base import StrictModel
from openharness.protocols.messages import ConversationMessage
from openharness.protocols.usage import UsageSnapshot


class ApiTextDeltaEvent(StrictModel):
    """Incremental text from the model during streaming."""

    type: Literal["text_delta"] = "text_delta"
    text: str


class ApiMessageCompleteEvent(StrictModel):
    """Terminal event: the model finished generating.

    Carries the full assembled assistant message (all content blocks), the
    final ``UsageSnapshot``, and the canonical Anthropic ``stop_reason``. The
    engine reads ``stop_reason`` to decide whether to continue the tool loop
    (``tool_use``) or stop (``end_turn`` / ``max_tokens`` / ``stop_sequence``).
    """

    type: Literal["message_complete"] = "message_complete"
    message: ConversationMessage
    usage: UsageSnapshot
    stop_reason: Literal["end_turn", "tool_use", "max_tokens", "stop_sequence"]


class ApiRetryEvent(StrictModel):
    """Emitted by the API client on retryable failure (429 / 5xx / transient).

    Surfaced so the UI can render "retrying..." rather than appearing stalled.
    """

    type: Literal["retry"] = "retry"
    attempt: int = Field(ge=1)
    delay_seconds: float = Field(ge=0)
    error: str


class ToolExecutionStartedEvent(StrictModel):
    """Emitted by ``run_query`` immediately before invoking a tool.

    Caller can render "[Bash] running ..." or similar before the tool's body
    runs. ``tool_use_id`` ties this event to the originating ``ToolUseBlock``
    so UIs can correlate Started/Completed pairs across interleaved deltas.
    """

    type: Literal["tool_execution_started"] = "tool_execution_started"
    tool_use_id: str
    tool_name: str
    tool_input: dict[str, Any]


class ToolExecutionCompletedEvent(StrictModel):
    """Emitted by ``run_query`` after a tool finishes (success or recoverable
    failure).

    ``output`` is the same string the LLM will see in the next-turn
    ``ToolResultBlock``; ``is_error`` mirrors ``ToolResult.is_error``. Programming
    errors from inside ``execute`` propagate as raised exceptions instead of
    surfacing here -- per D8.5.
    """

    type: Literal["tool_execution_completed"] = "tool_execution_completed"
    tool_use_id: str
    tool_name: str
    output: str
    is_error: bool


class BoundaryViolationEvent(StrictModel):
    """Typed report that a verified runtime boundary rejected an effect."""

    type: Literal["boundary_violation"] = "boundary_violation"
    tool_use_id: str
    tool_name: str
    dimension: str
    requested: str
    evidence: str


class PermissionParkedEvent(StrictModel):
    """The turn stopped because an exact permission request needs a person."""

    type: Literal["permission_parked"] = "permission_parked"
    request_id: str
    tool_use_id: str
    tool_name: str
    delta_kind: str
    delta_value: str
    profile_fingerprint: str
    enforcement: dict[str, Any] = Field(default_factory=dict)
    boundary_fingerprint: str | None = None
    backend: str | None = None
    backend_fingerprint: str | None = None
    final_arguments: dict[str, Any]
    data_sources: tuple[str, ...]
    data_destinations: tuple[str, ...]
    boundary_facts: dict[str, Any] | None = None
    reason: str
    messages: list[ConversationMessage]


class ConversationCompleteEvent(StrictModel):
    """P6+-T1: yielded as the FINAL event of ``run_query`` when the
    loop exits (end_turn reached or max_turns hit).

    Carries the full conversation messages list so callers (notably
    the ``oh`` REPL) can carry forward state across turns —
    just plug ``event.messages`` back in as ``initial_messages``
    for the next ``run_query`` invocation.

    the non-interactive runtime's renderer ignores this event (no visible output);
    it's metadata for callers that care about multi-turn state.
    """

    type: Literal["conversation_complete"] = "conversation_complete"
    messages: list[ConversationMessage]


# Discriminated union -- Pydantic dispatches by the ``type`` field at parse time.
# Same pattern as ``ContentBlock`` in content.py.
ApiStreamEvent: TypeAlias = Annotated[
    ApiTextDeltaEvent
    | ApiMessageCompleteEvent
    | ApiRetryEvent
    | ToolExecutionStartedEvent
    | ToolExecutionCompletedEvent
    | BoundaryViolationEvent
    | PermissionParkedEvent
    | ConversationCompleteEvent,
    Field(discriminator="type"),
]
